 CREATE DATABASE TAREAPROGRA

 USE TAREAPROGRA

 CREATE TABLE SCHOOL (
  SchoolId INT PRIMARY KEY,
  SchoolNombre VARCHAR(50),
  descripcion VARCHAR(1000),
  direccion VARCHAR(50),
  telefono VARCHAR(50),
  PostCode VARCHAR(50),
  PostAddress VARCHAR(50),
)

CREATE TABLE CLASS (
  ClassId INT PRIMARY KEY,
  SchoolId INT NOT NULL FOREIGN KEY REFERENCES SCHOOL (SchoolId),
  ClassNombre VARCHAR(50),
  Descripcion VARCHAR(1000),
)

CREATE TABLE COURSE (
  CourseId INT PRIMARY KEY,
  CourseNombre VARCHAR(50),
  SchoolId INT NOT NULL FOREIGN KEY REFERENCES SCHOOL (SchoolId),
  Descripcion VARCHAR(1000),
)

CREATE TABLE TEACHER(
  TeacherId INT PRIMARY KEY,
  SchoolId INT NOT NULL FOREIGN KEY REFERENCES SCHOOL (SchoolId),
  TeacherNombre VARCHAR(50),
  Descripccion VARCHAR(1000),
)

CREATE TABLE STUDENT_COURSES(
  StudentId INT NOT NULL FOREIGN KEY REFERENCES STUDENT (StudentId),
  CourseId INT NOT NULL FOREIGN KEY REFERENCES COURSE (CourseId),
)

CREATE TABLE TEACHER_COURSES(
  TeacherId INT NOT NULL FOREIGN KEY REFERENCES TEACHER (TeacherId),
  CourseId INT NOT NULL FOREIGN KEY REFERENCES COURSE (CourseId),
)

CREATE TABLE STUDENT(
  StudentId INT PRIMARY KEY,
  ClassId INT NOT NULL FOREIGN KEY REFERENCES CLASS (ClassId),
  StudentNombre VARCHAR(50),
  TotalGrade FLOAT,
  Direccion VARCHAR(100),
  Phone VARCHAR(20),
  EMail VARCHAR(100),
)

CREATE TABLE GRADE(
  GradeId INT PRIMARY KEY,
  StudentId INT NOT NULL FOREIGN KEY REFERENCES STUDENT (StudentId),
  CourseId INT NOT NULL FOREIGN KEY REFERENCES COURSE (CourseId),
  Grade FLOAT,
  Comment VARCHAR(1000),
)